services:

  postgres:
    image: postgres:15.4
    networks:
      default:
        aliases:
          - postgresql.db.service
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

  server:
    build:
      context: ./
      dockerfile: docker/dns/Dockerfile
    networks:
      default:
        aliases:
          - dns.service
    env_file:
      - .env
    depends_on:
      - postgres
    command: python manage.py rundnsserver
    volumes:
      - static_volume:/app/static/

  admin:
    build:
      context: ./
      dockerfile: docker/dns/Dockerfile
    networks:
      default:
        aliases:
          - admin.service
    env_file:
      - .env
    depends_on:
      - postgres
    expose:
      - 8000
    volumes:
      - static_volume:/app/static/

  web:
    build:
      context: ./
      dockerfile: ./docker/admin/Dockerfile
    volumes:
      - static_volume:/app/static/


volumes:
  postgres_volume:
  static_volume: